[package]
name = "rust_sat_ip_test"
version = "0.1.0"
authors = ["Eros Candelaresi <eros@candelaresi.de>"]
edition = "2018"

[dependencies]
log = "0.4.6"
log4rs = "0.8.1"
tokio = "0.1.13"
futures = "0.1.25"
hyper = "0.12"
http = "0.1.14"
httparse = "1.3.3"